- protocol.html
This does *not* change the actual RDF types used for these subscription types, but it does change the labels used in the HTML document to refer to these types consistently
> Make the subscription type labels more consistent

- protocol.html
Given https://github.com/solid/notifications/issues/24 and discussion at the 2021-12-16 panel meeting, it is likely that the gateway API will change. This PR simply indicates that the feature, as described, is at risk. This will allow the publication of a ~FPWD of this document while allowing conversation on #24 to proceed in its own timeframe.
> Indicate that the gateway API is at risk

- protocol.html
Resolves #24
This entirely removes the Gateway endpoint, replacing it with an RDF-based resource that can be used by clients to find the appropriate subscription API, based on the features and protocols supported by the client.
For example, the following RDF structure could replace the Gateway endpoint:
```turtle
@prefix solid: <http://www.w3.org/ns/solid/terms#> .
@prefix notify: <http://www.w3.org/ns/solid/notifications#> .
<>
a solid:StorageMetadata ;
notify:hasWebSocketNotification <#websocketNotification> ;
notify:hasWebHookNotification <#webhookNotification> ;
notify:hasLinkedDataNotification <https://ldn.example/Metadata> .
<#websocketNotification>
a notify:WebSocketSubscription2021 ;
notify:endpoint <https://websocket.example/subscription> ;
notify:features notify:state, …
```
> Replace separate gateway endpoint with RDF-based protocol discovery

- protocol.html
In reply to ACTION https://github.com/solid/notifications-panel/blob/main/meetings/2022-01-27.md#server-accepts-get-head-and-options-requests-targeting-subscription-resource
> Add server-subscription-resource-safe-methods

- protocol.html
The use cases section was removed earlier, but the ToC still refers to it.
> Remove incorrect table of contents item

- eventsource-subscription-2021.html
- linkeddatanotifications-subscription-2021.html
- protocol.html
- websocket-subscription-2021.html
A partial solution to #44 
To see the difference:
1. Open a new browser tab
2. Open dev tools
* set throttling to 2G
* disable cache
3. Paste https://solid.github.io/notifications/protocol in the address bar and navigate
The page will not render until the whole `dokieli.js` gets loaded, which with throttling set to 2G will take a while.
For the version in this PR, repeat steps 1. & 2.
3. Paste https://elf-pavlik.github.io/notifications/protocol in the address bar and navigate
The page will render before `dokieli.js` finishes loading.
To fully solve #44 we should follow Ruben's suggestion captured in https://github.com/solid/notifications-panel/issues/36 and inject stylesheet from the javascript.
> make dokieli.js async

- README.md
- protocol.html
This is an action from the [Meeting on 3 March 2022](https://github.com/solid/notifications-panel/blob/main/meetings/2022-03-10.md#publication-of-notifications-protocol-fpwd) in which the panel decided to move the individual subscription types out of the protocol document. This PR also clarifies the requirements/guidelines for defining new subscription types.
> Separate subscription type definitions from protocol document

- protocol.html
This removes the concept of a "Solid Storage Metadata Resource" (which doesn't exist). Should such a concept be introduced in the Solid Protocol, any relationship to notifications can be added there.
> Clarify discovery mechanism as independent of Solid Metadata Resources

- streaming-http-subscription-2021.bs
It adds annotations following the  Turtle example in: https://github.com/solid/specification-tests#annotations
It follows embedding in HTML as recommended in Turtle spec: https://www.w3.org/TR/turtle/#in-html
> added Turtle with anotations for specification-tests

- README.md
This link is currently broken. This PR fixes it.
> Fix broken link for WebHook subscription type

- README.md
- protocol.html
We add text guiding Subscription Type publishers to register the Subscription Type information with the Solid project.
This is the first part of the action item on author guidance from the notifications-panel meeting on 31-03-2022, only containing subscription type registration guidance. Guidance on how one might go about creating a new protocol shall be added later (might require us to write a primer first before linking it from the standard).
> Guidance to Subscription Type Publishers 1

- .gitignore
- webpush-subscription-2022-flow.mmd
- webpush-subscription-2022.bs
Dear all,
I propose a first draft for defining the `WebPushSubscription2022` type, based on my [original submission](https://uvdsl.solid.aifb.kit.edu/conf/2022/icwe/demo), as decided in the Notifications Panel meeting on 2022-03-22 (see https://github.com/solid/notifications-panel/pull/52).
This PR addresses #35.
While writing this draft, I noticed that several existing issues need to be resolved prior to finishing this draft, including but not limited to  #36, #62 and #63.
I  deeply appreciate any feedback.
> Define WebPushSubscription2022 type for Solid Notifications

- websocket-subscription-2021.html
"source" is tripping me up. Shouldn't this example use the `wss` scheme instead of `https`?
> Use wss scheme in notification-subscription-response example

- protocol.html
Follows of ACTION of https://github.com/solid/notifications-panel/blob/main/meetings/2022-08-18.md#subscription-request-response , 
There are no major changes in the functionality for implementations, but I had to rework this section a bit to clarify the actual requirements for client and server.
* `#client-subscription-request-statements` : requiring the client to use a particular set of statements in the request payload ( `#subscription-request-statements`).
* `#subscription-request-statements` : defining the statements to use in the subscription request payload.
* `#server-subscription-request-payload-invalid` - requiring the server to reject a subscription request that does not conform to expected payload.
> Add subscription-request-statements and server processing

- protocol.html
Resolves issue #58 by working with the notion of notification channel:
* Adds definition for notification-channel-resource.
* Describes notification-channel-discovery via notification-channel-resource (servers can advertise link relations `describedby` ( server-link-resource-notification-channel ) and `http://www.w3.org/ns/solid#storageDescription` ( server-link-storage-notification-channel ) and notification-channel description.
* Adds notification-channel-conformance
> Update notification channel discovery and conformance

- protocol.html
The [current introduction](https://solid.github.io/notifications/protocol#introduction) is quite verbose and strays into areas that it really doesn't need to address. This attempts to simplify and make the introduction more concise.
> Simplify and clarify introduction

- protocol.html
Updated to indicate that the subscription-resource is used for subscription requests.
> Clarify subscription-resource definition

- notifications-flow-protocol.mmd
- notifications-flow-source.mmd
- notifications-flow-target.mmd
- protocol.html
This simplifies the flow diagrams, removing those actors that are out of scope for this specification and placing the common portions of the flow into its own diagram. And given that `source` and `target` are not defined until later in the document, this uses more generally understood terminology to describe the categories of interaction.
PR towards https://github.com/solid/notifications/issues/77
> Simplify flow diagrams

- websocket-subscription-2021-flow.mmd
- websocket-subscription-2021.html
This adjusts the current WebSocket subscription type diagram to align with the diagrams in the Notification Protocol document. The updated flow looks like this
> Align WebSocket diagram to Notification Protocol diagram

- webhook-subscription-2021.md
As discussed and action of meeting: https://github.com/solid/notifications-panel/blob/main/meetings/2022-11-24.md#webhooks
There are existing implementations, including
* https://github.com/o-development/solid-webhook-client
* https://github.com/CommunitySolidServer/CommunitySolidServer/tree/versions/6.0.0
They should be able to reference specific version currently implemented.
> Tag WebhookSubscription2021 as Version 0.1

- protocol.html
PR follows https://github.com/solid/notifications/pull/120#issuecomment-1337330828 .
> Update classes-of-products interoperability

- protocol.html
Action of https://github.com/solid/notifications-panel/blob/main/meetings/2022-12-01.md#add-solid-notification-json-ld-context .
* Renames feature `expiration` to `endTime` (and editorial update to definition).
* Adds feature `startTime`.
* Updates `client-subscription-request` (editorial).
* Updates `subscription-request-data-model`.
* Adds `server-subscription-response`.
* Adds `subscription-response-data-model`.
---
[Preview](http://htmlpreview.github.io/?https://github.com/solid/notifications/blob/cb18f48fff1d2b79b655f0ad322a82f8704c56e8/protocol.html) | [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fnotifications%2Fmain%2Fprotocol.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fnotifications%2Fcb18f48fff1d2b79b655f0ad322a82f8 …
> Update subscription data model

- notifications-flow-protocol.mmd
- notifications-flow-source.mmd
- notifications-flow-target.mmd
```mermaid
sequenceDiagram
participant Subscription Client
participant Resource Server
participant Subscription Server
Subscription Client ->> Resource Server: HEAD Resource (topic)
Resource Server ->> Subscription Client: HTTP Link rel="describedby"
Subscription Client ->> Resource Server: GET Description Resource
Resource Server ->> Subscription Client: Description Resource
Subscription Client ->> Subscription Server: Subscription Request
Subscription Server ->> Subscription Client: Subscription Response (with Notification Channel)
```
```mermaid
sequenceDiagram
participant Notification Receiver
participant Notification Sender
loop while subscription active
Notification Receiver ->> Notification Sender: Establish connection to the receiveFrom
Notification Sender -->> Notification …
```
> update sequence diagrams

- ldn-channel-2023.html
This ED defines the `LDNChannel2023` Notification Channel Type. This specification deprecates [LinkedDataNotifications Subscription 2021](https://solid.github.io/notifications/linkeddatanotifications-subscription-2021).
---
[Preview](https://htmlpreview.github.io/?https://github.com/solid/notifications/blob/eced5e10b2d25ffe013310f5b3f51102e04cb627/ldn-channel-2023.html)
> Add ldn-channel-2023 ED

- biblio.json
- partials/terminology.bs
- streaming-http-channel-2023.bs
- webhook-channel-2023.bs
> extracted parts which bikeshed can reuse across the specs

- protocol.html
As per [Solid CG 2023-05-03 meeting](https://github.com/solid/specification/blob/d9c7d62b32aef199b3b84f29840bba93bd6fe5e9/meetings/2023-05-03.md#solid-notifications-vocab-and-json-ld-context) decision with @timbl (as W3C Team contact), we'll need to change the JSON-LD context URL to something like `ns/solid/notifications-context/v1`.
This is a "Corrections that do not add new features" as per https://www.w3.org/2021/Process-20211102/#class-3 , in particular:
>makes conforming data, processors, or other conforming agents become non-conforming according to the new version
This entails that the change here in the Editor's Draft is towards the next release of the Notifications Protocol (0.3.0).
Since the JSON-LD context was never published, I don't suspect any implementation depending on it …
> Change JSON-LD context URI in Solid Notifications Protocol

- eventsource-channel-2023.html
- ldn-channel-2023.html
- streaming-http-channel-2023.bs
- webhook-channel-2023.bs
- webpush-subscription-2022.bs
- websocket-channel-2023.html
PR updates the SotD section given that the [Solid CG Charter](https://www.w3.org/community/solid/charter/) supersedes Solid Process.
> Remove mention of Solid Process from SotD

- .github/workflows/ci-config.yml
- logo.include
- streaming-http-channel-2023.bs
- streaming-http-subscription-2021.bs
- webhook-channel-2023.bs
- webpush-subscription-2022.bs
Previews:
* https://elf-pavlik.github.io/notifications/streaming-http-channel-2023
* https://elf-pavlik.github.io/notifications/webhook-channel-2023
* https://elf-pavlik.github.io/notifications/webpush-subscription-2022
BTW: Later this week, I plan to PR WebPushChannel2023 since I have been implementing it lately.
> use CG-DRAFT template
